### ISSUE TITLE
Carousels not auto-rotating any more

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#387]
The carousels (page header carousels and carousel modules) used to auto-rotate - that seems to have stopped for some reason.

**Comment by holliscooper-cgu** [comment]
This seems to have been resolved, but now the Events module is auto-rotating as well - and it shouldn't.

**Comment by davekellam** [comment]
Believe this was fixed, but not closed.

**Comment by Jessdwilson** [comment]
@davekellam the events module on the homepage appears to still be auto-rotating 

![Uploading Screen Shot 2017-02-20 at 8.53.48 AM.png…]()

**Comment by davekellam** [comment]
Ahh, seems to be affecting Safari and not Chrome.

**Comment by davekellam** [comment]
It seemed to have been partially fixed, the events module slider is a slightly different setup from the homepage. I _think_ this is fixed now. It seems to have stemmed from some general knock-on effects regarding the separation of cgu-core concerns from the main cgu theme.

**Comment by holliscooper-cgu** [comment]
The timeline modules are acting weird - they go to the end, and then go in reverse, rather than starting over at the beginning. See the homepage for an example.
