### ISSUE TITLE
mobile display: width not narrow enough

### ISSUE THREAD

**Issue by holliscooper-cgu** [ObjectiveSubject/cgu#399]
Using both Google's mobile friendly tool, and through testing on my phone, it seems like the logo isn't shrinking enough to fit the browser window (or something is keeping the page from adjusting to the proper width). 

See: https://search.google.com/search-console/mobile-friendly?id=PKEv6MBCFnXDFrsjGwoy_Q

**Comment by davekellam** [comment]
@holliscooper-cgu where did you get the above screenshot from? I don't see that happening, but I am noticing the container issue (seems a bit too wide). Appears that this is only affecting the homepage, so it's likely one of the modules there throwing things off (possibly the recent fixes to the slider at the top).

**Comment by davekellam** [comment]
Tracked down the logo issue. It was getting cutoff on smaller viewports, like iPhone 5. That should be fixed now.

I don't think that's the cause of the "Content wider than screen" issue. Having some trouble tracking it down. The page seems fine on mobile most of the time for me, but every once in awhile, I get a bit of horizontal scrolling, like extra padding is sneaking in from somewhere.

**Comment by davekellam** [comment]
I'm currently thinking this is the related to the width on `.slick-track`. If we run some js to highlight elements outside of document width, we get the various sliders returned.

```js
var docWidth = document.documentElement.offsetWidth;

[].forEach.call(
  document.querySelectorAll('*'),
  function(el) {
    if (el.offsetWidth > docWidth) {
      console.log(el);
    }
  }
);
```

I'm not sure why Google is flagging the home page, but not other pages with sliders. So, it could be that there's still something else hidden causing the overflow, which I haven't tracked down yet.

**Comment by kpettinga** [comment]
@davekellam the `.slick-track` elements are wider than the document width BUT they are within containers that conform to the width of the screen and hide anything that overflows in mobile sizes.

@holliscooper-cgu can you confirm that you're still seeing this issue on mobile? I've tested it in browser as well as on an Android device.
